# Load Packages and Data

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#load csv containing return data on assets
assets = pd.read_csv('/home/Portfolio_2.csv',header='infer',index_col='Date') 

In [4]:
assets.head(5)

GOOGL         FB       NFLX        AMZN       BBBY  \
Date                                                                  
2015-04-01  549.489990  81.669998  59.017143  370.260010  73.779182   
2015-04-02  541.309998  81.559998  59.154285  372.250000  74.233482   
2015-04-06  543.950012  82.440002  60.330002  377.040009  74.900414   
2015-04-07  544.859985  82.320000  60.494286  374.410004  74.136803   
2015-04-08  548.840027  82.279999  63.049999  381.200012  75.084068   

                  COST       DLTR        FOX       Gold        PEP  
Date                                                                
2015-04-01  139.591400  81.300003  31.535204  68.523880  87.257195  
2015-04-02  140.882874  81.120003  32.055969  67.968102  87.807785  
2015-04-06  141.691223  80.980003  32.287418  69.050911  88.532707  
2015-04-07  141.022232  80.580002  32.104183  67.824371  88.284943  
2015-04-08  141.226639  83.529999  32.046318  67.345238  88.119774

In [5]:
assets.tail(5) 

GOOGL          FB        NFLX         AMZN       BBBY  \
Date                                                                      
2018-03-23  1026.550049  159.389999  300.940002  1495.560059  21.299999   
2018-03-26  1054.089966  160.059998  320.350006  1555.859985  21.070000   
2018-03-27  1006.940002  152.220001  300.690002  1497.050049  20.250000   
2018-03-28  1005.179993  153.029999  285.769989  1431.420044  20.610001   
2018-03-29  1037.140015  159.789993  295.350006  1447.339966  20.990000   

                  COST       DLTR        FOX       Gold         PEP  
Date                                                                 
2018-03-23  180.839996  91.949997  35.450001  83.919998  106.150002  
2018-03-26  187.220001  95.209999  36.580002  85.220001  106.809998  
2018-03-27  183.149994  93.629997  36.080002  83.660004  107.639999  
2018-03-28  183.610001  93.910004  35.500000  82.320000  109.180000  
2018-03-29  188.429993  94.900002  36.369999  83.239998  109.150002

# Calculate Daily Returns 

In [6]:
returns = (assets/assets.shift(1))-1
returns.head()

GOOGL        FB      NFLX      AMZN      BBBY      COST  \
Date                                                                     
2015-04-01       NaN       NaN       NaN       NaN       NaN       NaN   
2015-04-02 -0.014887 -0.001347  0.002324  0.005375  0.006158  0.009252   
2015-04-06  0.004877  0.010790  0.019875  0.012868  0.008984  0.005738   
2015-04-07  0.001673 -0.001456  0.002723 -0.006975 -0.010195 -0.004721   
2015-04-08  0.007305 -0.000486  0.042247  0.018135  0.012777  0.001449   

                DLTR       FOX      Gold       PEP  
Date                                                
2015-04-01       NaN       NaN       NaN       NaN  
2015-04-02 -0.002214  0.016514 -0.008111  0.006310  
2015-04-06 -0.001726  0.007220  0.015931  0.008256  
2015-04-07 -0.004940 -0.005675 -0.017763 -0.002799  
2015-04-08  0.036610 -0.001802 -0.007064 -0.001871

# Check Distribution of Returns

In [7]:
returns.hist(bins=100)
plt.show()

# Calculate Log Returns

In [8]:
log_returns = np.log((assets/assets.shift(1)))

In [9]:
log_returns.head()

GOOGL        FB      NFLX      AMZN      BBBY      COST  \
Date                                                                     
2015-04-01       NaN       NaN       NaN       NaN       NaN       NaN   
2015-04-02 -0.014998 -0.001348  0.002321  0.005360  0.006139  0.009209   
2015-04-06  0.004865  0.010732  0.019680  0.012786  0.008944  0.005721   
2015-04-07  0.001672 -0.001457  0.002719 -0.007000 -0.010247 -0.004733   
2015-04-08  0.007278 -0.000486  0.041379  0.017973  0.012696  0.001448   

                DLTR       FOX      Gold       PEP  
Date                                                
2015-04-01       NaN       NaN       NaN       NaN  
2015-04-02 -0.002216  0.016379 -0.008144  0.006290  
2015-04-06 -0.001727  0.007194  0.015806  0.008222  
2015-04-07 -0.004952 -0.005691 -0.017922 -0.002802  
2015-04-08  0.035955 -0.001804 -0.007089 -0.001873

In [10]:
log_returns.mean()*252

GOOGL    0.212306
FB       0.224318
NFLX     0.538202
AMZN     0.455631
BBBY    -0.420122
COST     0.100268
DLTR     0.051696
FOX      0.047673
Gold     0.065021
PEP      0.074819
dtype: float64

# Covariance Matrix

In [11]:
log_returns.cov()*252

GOOGL        FB      NFLX      AMZN      BBBY      COST      DLTR  \
GOOGL  0.051703  0.037923  0.040084  0.037761  0.006759  0.014809  0.017474   
FB     0.037923  0.063865  0.041359  0.041199  0.006268  0.012379  0.015795   
NFLX   0.040084  0.041359  0.174764  0.048329  0.011944  0.016129  0.022053   
AMZN   0.037761  0.041199  0.048329  0.077447  0.004387  0.013007  0.015140   
BBBY   0.006759  0.006268  0.011944  0.004387  0.099406  0.016719  0.031556   
COST   0.014809  0.012379  0.016129  0.013007  0.016719  0.034535  0.021681   
DLTR   0.017474  0.015795  0.022053  0.015140  0.031556  0.021681  0.079864   
FOX    0.016526  0.018267  0.023956  0.020239  0.020358  0.011282  0.018325   
Gold   0.003415  0.004893  0.009260  0.005545  0.002565 -0.002043 -0.000960   
PEP    0.011622  0.011475  0.011262  0.010551  0.004672  0.010648  0.010233   

            FOX      Gold       PEP  
GOOGL  0.016526  0.003415  0.011622  
FB     0.018267  0.004893  0.011475  
NFLX   0.023956  0.009260  0.011262  
AMZN   0.020239  0.005545  0.010551  
BBBY   0.020358  0.002565  0.004672  
COST   0.011282 -0.002043  0.010648  
DLTR   0.018325 -0.000960  0.010233  
FOX    0.060808  0.000715  0.008245  
Gold   0.000715  0.127163  0.006395  
PEP    0.008245  0.006395  0.017353

# Correlation Matrix

In [12]:
log_returns.corr()

GOOGL        FB      NFLX      AMZN      BBBY      COST      DLTR  \
GOOGL  1.000000  0.659948  0.421682  0.596727  0.094283  0.350461  0.271933   
FB     0.659948  1.000000  0.391481  0.585806  0.078667  0.263593  0.221170   
NFLX   0.421682  0.391481  1.000000  0.415408  0.090621  0.207611  0.186670   
AMZN   0.596727  0.585806  0.415408  1.000000  0.050001  0.251497  0.192502   
BBBY   0.094283  0.078667  0.090621  0.050001  1.000000  0.285347  0.354165   
COST   0.350461  0.263593  0.207611  0.251497  0.285347  1.000000  0.412833   
DLTR   0.271933  0.221170  0.186670  0.192502  0.354165  0.412833  1.000000   
FOX    0.294732  0.293131  0.232387  0.294913  0.261850  0.246201  0.262965   
Gold   0.042117  0.054295  0.062117  0.055871  0.022818 -0.030832 -0.009527   
PEP    0.388017  0.344700  0.204512  0.287823  0.112488  0.434950  0.274878   

            FOX      Gold       PEP  
GOOGL  0.294732  0.042117  0.388017  
FB     0.293131  0.054295  0.344700  
NFLX   0.232387  0.062117  0.204512  
AMZN   0.294913  0.055871  0.287823  
BBBY   0.261850  0.022818  0.112488  
COST   0.246201 -0.030832  0.434950  
DLTR   0.262965 -0.009527  0.274878  
FOX    1.000000  0.008136  0.253833  
Gold   0.008136  1.000000  0.136136  
PEP    0.253833  0.136136  1.000000

# Random Weights via Monte Carlo Method

In [13]:
number_assets = len(assets.columns)
Rf = .015
weight_log=[]
port_info = np.zeros((3,25000))
for x in range(25000):   
    weights = np.random.random(number_assets)
    weights /= np.sum(weights)
    weight_log.append(weights)
    pret = np.sum(weights*log_returns.mean())*252
    pvol = np.sqrt(np.dot(weights.T,np.dot(log_returns.cov()*252, weights)))
    port_info[0,x] = pvol
    port_info[1,x] = pret
    port_info[2,x] =(pret - Rf)/pvol
    
port_info,weight_log 

(array([[0.14803552, 0.14544794, 0.16954159, ..., 0.15182479, 0.14640746,
         0.13753712],
        [0.04405207, 0.12090834, 0.20179697, ..., 0.12170915, 0.13369168,
         0.02586647],
        [0.19625067, 0.72815293, 1.10177666, ..., 0.70284404, 0.81069421,
         0.07900753]]),
 [array([0.06207041, 0.09782383, 0.07256424, 0.00562903, 0.16534642,
         0.00420297, 0.19173161, 0.07312624, 0.15775206, 0.1697532 ]),
  array([0.3081686 , 0.01216073, 0.02746311, 0.02662198, 0.03021748,
         0.03005231, 0.12477809, 0.07249027, 0.19568898, 0.17235845]),
  array([0.15241591, 0.17230283, 0.1261453 , 0.15982202, 0.07118158,
         0.03787673, 0.04860317, 0.10405263, 0.08539271, 0.04220712]),
  array([0.18191889, 0.11033439, 0.19491422, 0.00958951, 0.08365576,
         0.10184577, 0.13832055, 0.00599586, 0.08996558, 0.08345946]),
  array([0.02201597, 0.14614501, 0.0790309 , 0.10626366, 0.06002796,
         0.08599274, 0.12093202, 0.12889467, 0.16798062, 0.08271644]),
  array([0

In [14]:
max_sharpe_idx = np.argmax(port_info[2])
sdp, rp = port_info[0,max_sharpe_idx], port_info[1,max_sharpe_idx]
max_sharpe_allocation = pd.DataFrame(weight_log[max_sharpe_idx],index=returns.columns,columns=['allocation'])
max_sharpe_allocation.allocation = [round(i*100,2)for i in max_sharpe_allocation.allocation]
max_sharpe_allocation = max_sharpe_allocation.T

min_vol_idx = np.argmin(port_info[0])
sdp_min, rp_min = port_info[0,min_vol_idx], port_info[1,min_vol_idx]
min_vol_allocation = pd.DataFrame(weight_log[min_vol_idx],index=returns.columns,columns=['allocation'])
min_vol_allocation.allocation = [round(i*100,2)for i in min_vol_allocation.allocation]
min_vol_allocation = min_vol_allocation.T

max_sharpe_allocation,min_vol_allocation

(            GOOGL    FB   NFLX   AMZN  BBBY  COST  DLTR  FOX  Gold    PEP
 allocation  24.66  6.59  21.83  23.14  0.38  1.03  7.17  0.2  0.22  14.78,
             GOOGL     FB  NFLX  AMZN  BBBY   COST  DLTR    FOX  Gold    PEP
 allocation   1.98  11.56   0.1  4.54  5.71  12.84  9.87  15.71  9.19  28.49)

In [15]:
plt.figure(figsize=(10, 7))
plt.scatter(port_info[0,:],port_info[1,:],c=port_info[2,:],cmap='Spectral', marker='o', s=10, alpha=0.3)
plt.colorbar(label='Sharpe Ratio')
plt.scatter(sdp,rp,marker='*',color='b',s=500, label='Maximum Sharpe ratio')
plt.scatter(sdp_min,rp_min,marker='*',color='r',s=500, label='Minimum volatility')
plt.title('Portfolio Optimization - Efficient Frontier')
plt.grid(True)
plt.xlabel('Annualized Volatility')
plt.ylabel('Annualized Returns')
plt.legend(labelspacing=0.8)
plt.show()